version: '3.8'

services:
  docs_baio:
    build:
      context: .
      dockerfile: Dockerfile.documentation
    ports:
      - "8008:8008"
    volumes:
      - ./docs:/app/doc
      - ../docs:/app/docs # Output directory for GitHub Pages

    command: >
      /bin/sh -c "sphinx-autobuild /app/doc/source /app/docs --host 0.0.0.0 --port 8008 && touch /app/docs/.nojekyll"
